### ISSUE TITLE
SLACK CONNECTION FAILED Only absolute URLs are supported

### ISSUE THREAD

**Issue by mischaswyftx** [juliuscc/semantic-release-slack-bot#101]
Using Node 18 we get an error message from fetch "Only absolute URLs are supported"

Drop the version back to Node 16 to resolve the problem.

Output

[4:59:55 AM] [semantic-release] › ✖  SLACK CONNECTION FAILED Only absolute URLs are supported
--
  | AggregateError:
  | SemanticReleaseError: Only absolute URLs are supported
  | at module.exports (/workdir/node_modules/semantic-release-slack-bot/lib/postMessage.js:49:11)
  | at async module.exports (/workdir/node_modules/semantic-release-slack-bot/lib/success.js:123:3)
  | at /workdir/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
  | at async pluginsConf.<computed> [as success] (/workdir/node_modules/semantic-release/lib/plugins/index.js:80:11)
  | at async run (/workdir/node_modules/semantic-release/index.js:209:3)
  | at async module.exports (/workdir/node_modules/semantic-release/index.js:269:22)
  | error Command failed with exit code 1.
  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  | error Command failed.
  | Exit code: 1
  | Command: /usr/local/bin/node
  | Arguments: /opt/yarn-v1.22.19/lib/cli.js run semantic-release --debug
  | Directory: /workdir/apps/cron-coin-gecko
  | Output:
  |  
  | info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
  | 🚨 Error: The command exited with status 1

**Comment by juliuscc** [comment]
Can you share your configuration?

**Comment by marckraw** [comment]
I have the same problem,

node 18.15.x
semantic-release 20.x

this is the configuration
```
{
  "branches": [
    {
      "name": "master",
      "channel": "latest",
      "type": "release"
    },
    {
      "name": "beta",
      "channel": "beta",
      "prerelease": true
    }
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    "@semantic-release/github",
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": [
          "CHANGELOG.md",
          "package.json"
        ]
      }
    ],
    [
      "semantic-release-slack-bot",
      {
        "notifyOnSuccess": true,
        "notifyOnFail": true,
        "markdownReleaseNotes": true,
        "slackWebhook": ${SLACK_RELEASE_BOT_WEBHOOK_URL}
      }
    ]
  ]
}

I've checked that my github action have access to the proper env in `SLACK_RELEASE_BOT_WEBHOOK_URL`. And when i post to this proper url, with postman, it made it to slack. 
```

**Comment by marckraw** [comment]
What is interesting, when just hardcoding url into "slackWebhook" it works fine :). So probably something related to reading env variables of repository, by `semantic-release-slack-bot` or `semantic-release` itsef, is broken. (because like i said, i'm logging my `SLACK_RELEASE_BOT_WEBHOOK_URL` before release phase, and it is there)

**Comment by juliuscc** [comment]
Possibly stupid question but shouldn't the config be like this:
```diff
-        "slackWebhook": ${SLACK_RELEASE_BOT_WEBHOOK_URL}
+        "slackWebhook": "${SLACK_RELEASE_BOT_WEBHOOK_URL}"
```
