### ISSUE TITLE
slack bot should extend the accepted semantic release version to 21.0

### ISSUE THREAD

**Issue by tripodsan** [juliuscc/semantic-release-slack-bot#107]
when I build my project with the latest semantic-release, I get:

```
npm ERR! While resolving: semantic-release-slack-bot@4.0.0
npm ERR! Found: semantic-release@21.0.0
npm ERR! node_modules/semantic-release
npm ERR!   dev semantic-release@"21.0.0" from the root project
npm ERR!   peer semantic-release@">=18.0.0" from @semantic-release/changelog@6.0.3
npm ERR!   node_modules/@semantic-release/changelog
npm ERR!     dev @semantic-release/changelog@"6.0.3" from the root project
npm ERR!   6 more (@semantic-release/commit-analyzer, ...)
```

see https://github.com/semantic-release/semantic-release/releases/tag/v21.0.0

**Comment by tripodsan** [comment]
I don't mind creating PRs for every new major version. I think having a peer dependency is the right thing to do.
another possibility is to specify only the lower bound, for example like the git plugin does it:

https://github.com/semantic-release/git/blob/723952c5585deff27d46b5999774fe98ba083a19/package.json#L73-L75

**Comment by stefanmo** [comment]
If you don't mind me butting in, having to create PRs for each new major semantic release release (lol) is kind of bad, at least for our companies' use case.
We use semantic release for non-js projects as well so we don't have a package.json file. That means that we install semantic release latest in our CI, thus our CI pipeline are currently failing. So unless someone watches very closely semantic release and anticipates new major releases it isn't very friendly. And I'm not expecting premium support here, I know everyone is busy, it's just my 2 cents.

**Comment by juliuscc** [comment]
@stefanmo you raise a good case for this. Thanks @tripodsan for fixing a PR! 👍 ❤️

**Comment by tripodsan** [comment]
hi @juliuscc can you cut a new release, please?

**Comment by stefanmo** [comment]
@juliuscc can you please check the release? We are still stuck on this and have to do workarounds 😢

**Comment by PratikDarak** [comment]
@juliuscc It will be great if you can take a look at the failing pipeline. We are waiting for this release to enable the Slack integration with semantic release. Thank you!

**Comment by juliuscc** [comment]
Hi! Sorry for this taking so much time. I've been busy.

I have no idea why the CI-pipeline stopped working, or why my commit fixed it. But now it seems to work 😁 

Please let me know if there are any issues with the latest version and have a happy easter 🐣 ☀️
