### ISSUE TITLE
Use without the official semantic-release slack bot app

### ISSUE THREAD

**Issue by markov00** [juliuscc/semantic-release-slack-bot#14]
Hi, I was wondering if we can use this plugin without creating the incoming hook directly from your App.
Can I use my own created incoming hook?

**Comment by markov00** [comment]
Ok I've just tested on my setup and works correctly without using directly the App.
I know that you wrote that no data is stored on your server, but it was required from our security ops team

**Comment by juliuscc** [comment]
I hadn't considered this use case but it should not be any different. Great that it works for you and I will try to suggest this option in the documentation! Thanks!

**Comment by hannesrabo** [comment]
I clarified this in the README now.
