### ISSUE TITLE
SEMANTIC_RELEASE_PACKAGE is always needed

### ISSUE THREAD

**Issue by dijam** [juliuscc/semantic-release-slack-bot#18]
It seems you always need to provide env variable of `SEMANTIC_RELEASE_PACKAGE ` or `npm_package_name` needed. I assumed it will pick it up automatically form `package.json`.
Am I missing anything here?

**Comment by juliuscc** [comment]
Hi!

Could you include the output you are getting when you run semantic-release? I don't fully understand the description.

**Comment by juliuscc** [comment]
Are you running `npx semantic-release`? Because there might be an issue when using `npx` instead of npm-scripts.

**Comment by juliuscc** [comment]
Read more here: https://github.com/juliuscc/semantic-release-slack-bot/issues/4#issuecomment-502798477

**Comment by dijam** [comment]
Sorry for a undetailed issue. I wrote it in rush. I am running it via `codfish/semantic-release-action` in github actions and I double checked and yes, it is using `npx`.

**Comment by juliuscc** [comment]
I saw that you added an environmental variable, which seemed to work. Of course, that could be another one than the one in package.json, so we would recommend you **not** using `npx`.

Our recommendation is to add an npm-script like this in package.json: 

```
...
"semantic-release": "semantic-release",
...
```

Then you can switch `npx semantic-release` into `npm run semantic-release` in your github-action.

**Comment by mascardoso** [comment]
Hi @juliuscc and @dijam.
A quick question on this one.

I have the following configuration in my .releaserc:

```
"semantic-release-slack-bot",
            {
                "notifyOnSuccess": true,
                "notifyOnFail": true,
                "packageName": "@org/mypackagename",
                "slackWebhook": ...,
                "markdownReleaseNotes": true,
                "branchesConfig": [
                    {
                        "pattern": "main"
                    }
                ]
            }
```

Do I need anything else to make sure the package name gets displayed properly? I'm getting in slack notifications with a completely different org name than the one I hardcoded in `packageName`. Do I need to add somewhere `SEMANTIC_RELEASE_PACKAGE` ?

**Comment by juliuscc** [comment]
That is interesting. Does it seem like the rest of the config works? Does the org correspond to the one used in `package.json`?

The logic for choosing which packageName to display can be found here:

https://github.com/juliuscc/semantic-release-slack-bot/blob/7795cdaf0b607e9f7549bb8787250b6ce19a9c60/lib/success.js#L31-L32
