### ISSUE TITLE
JSON message format invalid

### ISSUE THREAD

**Issue by BeyondEvil** [juliuscc/semantic-release-slack-bot#19]
Was hit by this today:

```
[12:30:22 PM] [semantic-release] [semantic-release-slack-bot] › ℹ  JSON message format invalid
[12:30:22 PM] [semantic-release] › ✖  Failed step "success" of plugin "semantic-release-slack-bot"
[12:30:22 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[12:30:24 PM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #118: https://github.com/proxyco/aux-api/issues/118.
[12:30:24 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[12:30:24 PM] [semantic-release] › ℹ  Start step "fail" of plugin "semantic-release-slack-bot"
[12:30:24 PM] [semantic-release] [semantic-release-slack-bot] › ℹ  Notifying on fail skipped
[12:30:24 PM] [semantic-release] › ✔  Completed step "fail" of plugin "semantic-release-slack-bot"
[12:30:24 PM] [semantic-release] › ✖  SLACK CONNECTION FAILED:  
{ AggregateError: 
    SemanticReleaseError
        at fetch.then.then.catch.e (/usr/local/lib/node_modules/semantic-release-slack-bot/lib/postMessage.js:23:10)
    at /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }Exited with code 1
```

Config:
```json
{
    "branch": "master",
    "preset": "eslint",
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/git",
        "@semantic-release/github",
        [
            "semantic-release-slack-bot",
            {
                "notifyOnSuccess": true,
                "markdownReleaseNotes": true
            }
        ]
    ]
}
```

Only thing I can think of is that something in the release notes needed to be escaped. Problem is, the release notes was huge. 

Also, looking [here](https://github.com/juliuscc/semantic-release-slack-bot/blob/master/lib/postMessage.js#L18) I'm expecting to see what was the cause of the malformed JSON, but it seems that maybe the catch-clause swallowed that? 🤔  

I saw the other issue (#4) on the same topic, and afaict I'm running the latest version (v1.3.0). I installed it using `npm install -g semantic-release-slack-bot` (it's installed in a docker image that we use in our build pipeline, hence the global install).

Yep, truncate code is definitely there:
```bash
/usr/local/lib/node_modules/semantic-release-slack-bot/lib # cat success.js | grep truncate
			// truncate long messages
/usr/local/lib/node_modules/semantic-release-slack-bot/lib #
```

Where did you find the `3000` limit? All I could find was [this](https://api.slack.com/changelog/2018-04-truncating-really-long-messages).

There's also the "How to escape characters" [here](https://api.slack.com/docs/message-formatting) (maybe `slackify-markdown` deals with [that](https://github.com/jsarafajr/slackify-markdown/blob/master/src/slackify.js#L66)?).

**Comment by hannesrabo** [comment]
The 3000 character limit comes from [here](https://api.slack.com/reference/block-kit/blocks#section). The content of the message is sent in the `section` block which has a 3000 character limit.

I'm not sure about escaping certain characters outside of `slackify-markdown`. It does seem like this could be the issue and something to look into. Would you be able to provide a sample of text that breaks this feature as we haven't seen it in our own testing?

I created a small update to the package which appends the exception message directly to the initial log which should solve the problem of incomplete information.

**Comment by hannesrabo** [comment]
I also realized that we were truncating messages but reversed that effect before sending it off in case you were using the markdown feature. This has also been fixed now.

Let us know if this solves your issue 🙂

**Comment by BeyondEvil** [comment]
> The 3000 character limit comes from [here](https://api.slack.com/reference/block-kit/blocks#section). The content of the message is sent in the `section` block which has a 3000 character limit.

Got it, thanks!

> I'm not sure about escaping certain characters outside of `slackify-markdown`. It does seem like this could be the issue and something to look into. Would you be able to provide a sample of text that breaks this feature as we haven't seen it in our own testing?

Yeah, I'm going to spend a little bit of time to see if I can repro the issue locally. This happened in our production environment, so I can't really mess around in there too much. 😝 

> I created a small update to the package which appends the exception message directly to the initial log which should solve the problem of incomplete information.

Nice! 👍 

> I also realized that we were truncating messages but reversed that effect before sending it off in case you were using the markdown feature. This has also been fixed now.

Haha, damn, you're right. I didn't see that. 😆 That must've been it then, because we do use the mrkdwn. `"markdownReleaseNotes": true`

> Let us know if this solves your issue 🙂

I will, thanks!

Also, just FYI, I noticed that the `slackify-markdown` version (at least on v1.3.0) you're using is `1.1.1`, but the latest release is `2.1.0`

**Comment by BeyondEvil** [comment]
I had it happen again, with the latest version, this time I get:

`JSON message format invalid: invalid_blocks`

One interesting thing is that it doesn't happen on our develop branch (we run two different configs, one for stage releases and one for prod).

Here's the stage one:
```js
const changelog = "CHANGELOG.stage.md";

module.exports = {
    "branch": "develop",
    "preset": "eslint",
    "plugins": [
        "@semantic-release/commit-analyzer",
        [
            "@semantic-release/release-notes-generator",
            {
                "linkCompare": false,
                "writerOpts": {
                    "headerPartial": "{{#if isPatch}}##{{else}}#{{/if}} {{#if @root.linkCompare}}[Stage]({{@root.host}}/{{#if @root.owner}}{{@root.owner}}/{{/if}}{{@root.repository}}/compare/{{previousTag}}...{{currentTag}}){{else}}Stage{{/if}}{{#if title}} \"{{title}}\"{{/if}}{{#if date}} ({{date}}){{/if}}",
                    // This overrides: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-eslint/writer-opts.js#L24
                    "transform": (commit) => {
                        if (!commit.tag || typeof commit.tag !== `string`) { 
                            return 
                        }
                        commit.message = commit.message.replace(/NNN-\d+/g, '[$&](https://some.link.com/$&)');
                        commit.shortHash = commit.hash.substring(0, 7); 
                        return commit
                    }
                }
            }
        ],
        [
            "@semantic-release/changelog",
            {
                "changelogFile": changelog
            }
        ],
        [
            "@semantic-release/git",
            {
                "message": "${nextRelease.gitTag} released. [skip ci]\n\n${nextRelease.notes}",
                "assets": [changelog]
            }
        ],
        [
            "semantic-release-slack-bot",
            {
                "notifyOnSuccess": true,
                "markdownReleaseNotes": true,
                "onSuccessTemplate": {
                    "text": "Updates to $package_name has been released to *Stage*!\n\n$release_notes"
                }
            }
        ]
    ]
}
```

The only relevant difference (if I would guess) is that we're using `onSuccessTemplate` in the stage config.

**Comment by hannesrabo** [comment]
There is a difference in how those two categories are processed. The only real change that would affect the API is regarding which blocks are used. In the template setup, only the text block is used which might explain the complaints of invalid blocks.

If you update your template to:

```json
"onSuccessTemplate": {
    "type": "mrkdwn",
    "text": "[template]"
}
```

Slack will start to render the markdown which might give you the same exception in the staging environment?

**Comment by BeyondEvil** [comment]
> There is a difference in how those two categories are processed. The only real change that would affect the API is regarding which blocks are used. In the template setup, only the text block is used which might explain the complaints of invalid blocks.

Sorry, I'm not following. Categories?

Let's see if I understand. So in our stage config, we've specified _only_ the text block, so the plugin will only use that? And then in our prod config, where we haven't specified anything - the plugin will use all the blocks?

> If you update your template to:
> 
> ```json
> "onSuccessTemplate": {
>     "type": "mrkdwn",
>     "text": "[template]"
> }
> ```
> 
> Slack will start to render the markdown which might give you the same exception in the staging environment?

So the above change should be made to the stage config, to have it act more like the prod config? So that, hopefully, I can get the issue/error on stage?

**Comment by BeyondEvil** [comment]
I'm not successful in reproducing this after your changes, but I've put a modified version in our build environment that does a little more logging - so in case it happens again, we'll have some more information.
