### ISSUE TITLE
Truncating of long release notes not used on `onSuccessTemplate`

### ISSUE THREAD

**Issue by BeyondEvil** [juliuscc/semantic-release-slack-bot#21]
Maybe this is by design, but the truncating of long release notes only happens in the default case, if you use `onSuccessTemplate` the release notes will be sent to Slack in full.

**Comment by BeyondEvil** [comment]
ping @hannesrabo @juliuscc :)

**Comment by hannesrabo** [comment]
I will have a look at this as soon as I have time 🙂. It sounds like a good suggestion.

**Comment by BeyondEvil** [comment]
> I will have a look at this as soon as I have time 🙂. It sounds like a good suggestion.

I'm happy to create the PR if/when you give it a 👍

**Comment by juliuscc** [comment]
This is not by design. Also, I think the message should be truncated AFTER being markdown-transformed. Your PR would be very much appreciated 😊
