### ISSUE TITLE
Revise maxLength limit

### ISSUE THREAD

**Issue by AndrewLeedham** [juliuscc/semantic-release-slack-bot#26]
I believe the `maxLength` limit here: https://github.com/juliuscc/semantic-release-slack-bot/blob/master/lib/success.js#L9 is outdated [the docs](https://api.slack.com/changelog/2018-04-truncating-really-long-messages) seem to indicate that messages will be truncated on Slack's end at 40,000 characters.

Perhaps `maxLength` should be a config option and defaulted to 3000 as to not break things going forward, but allows a user to increase it as they please. Or maybe set it to 40,000 and bump the major version?

**Comment by hannesrabo** [comment]
Hi, this is something that has been previously discussed and it seems like the 3000 character limit still holds.

Here is the previous answer:

**Comment by hannesrabo** [comment]
Have you successfully tried the package with messages longer than 3000 character? I think it might be possible to have longer messages in case the section block is not used.

**Comment by AndrewLeedham** [comment]
Yes I have experimented with very long messages and more character can get through, but not anywhere near 40000. I have a feeling the limit is based on displayed characters not actual characters, e.g. for a link that displays text is shorter than the full label and URL markup. Just a theory but increasing the max limit definitely allowed more characters through in my testing.

**Comment by juliuscc** [comment]
AFAIK the limit for a message is 40000 characters. However, there is a much stricter limit to consider. When using a `section`, the character limit in the section is only 3000. Have you tried using a section with more than 3000 characters or only a message?

We are considering to allow a much larger character length when the user inputs a template, but if they use a `section` the limit should be the same.

**Comment by AndrewLeedham** [comment]
Hnmm I am on holiday this week, so I cannot check. But, I was using an attachment text field with more than 3000 characters, and saw more characters on slack with a higher max limit.

**Comment by AndrewLeedham** [comment]
Ok so sending this in a message body to slack:
```json
{
  "attachments": [
		{
			"title": "Length test",
			"text": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\nLorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil natus voluptates quisquam assumenda doloremque, ducimus iste ullam, ut dolorum eius delectus quibusdam maxime voluptatum a. Tenetur quasi iste vero ipsum!\n\n"
		}
  ]
}
```
outputs all of the paragraphs in the message which is around 5500 characters:
![image](https://user-images.githubusercontent.com/5557458/71584382-36f64d00-2b0a-11ea-9192-3aa38933026a.png)

**Comment by juliuscc** [comment]
The original limit is explicitly based on `section`, which of course is not mandatory in the case of using templates. Do you think it is possible to detect if there is a `section` in the template and limit that `section` to ~3000 characters, but otherwise raise the threshold to a much higher limit (~40,000)?

I do also agree that there should be a way to change the limits, but it should be very clear that it is an unsafe action, and having good defaults should be a priority.

Do you think it would be more clear that we do not recommend to change the config if it is called something like `UNSAFE_MAX_LENGTH` instead of `MAX_LENGTH`?

**Comment by AndrewLeedham** [comment]
`UNSAFE_MAX_LENGTH` sounds sensible to me. It seems that the new blocks api has some more stringent guidelines, e.g: the fields array in a section can have a maximum text length of 2000 and only contain 10 items. Should that be sanitised as well?

I was trying to find some-sort of schema, but slack does not seem to provide anything outside of some TypeScript types (which don't include property length). Also their own node webhook API does not do any sanitisation.

I guess there are a few options:
1. Always cap section text at 3000 characters, and default the `UNSAFE_MAX_LIMIT` to 3000 also but allow that to be configured for other fields at the users risk.
2. Have separate options for different types of fields, so the user can increase the section text limit as well as the attachments text etc.
3. Add exact sanitisation based on the limits specified in the docs, perhaps based on an JSON Schema file that would be easily updatable. Perhaps said schema can be overrode as an option, so the user can update limits as they see fit?

**Comment by juliuscc** [comment]
This problem is more complicated than I first thought 😅 Thanks for the extensive explanation!

I think option 3 is the nicest, but it might not be feasible. I would suggest doing option 1 one until a better solution comes. It will give the control and responsibility to the users of the plugin.
