### ISSUE TITLE
ssh repository field with no protocol causes ERR_INVALID_URL

### ISSUE THREAD

**Issue by AndrewLeedham** [juliuscc/semantic-release-slack-bot#30]
If the repository field is in the following format:
```jsonc
// package.json
{
  // ...
  "repository": "git@github.com:hello/world.git"
  // ...
}
```
it causes an `ERR_INVALID_URL` error, since `new URL('git@github.com/hello/world.git')` is expecting a protocol. So `new URL('ssh://git@github.com/hello/world.git')` would work.

Think there just needs to be a check for this case in `getRepoInfo`. Since, this format is one of the possible variants in https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes

**Comment by BeyondEvil** [comment]
I'm responsible for this bug. In my defense, I was expecting this module: [get-git-auth-url.js](https://github.com/semantic-release/semantic-release/blob/master/lib/get-git-auth-url.js) to handle all the cases. But I guess I was wrong. Thanks for the fix!
