### ISSUE TITLE
semantic-release v17 support

### ISSUE THREAD

**Issue by BeyondEvil** [juliuscc/semantic-release-slack-bot#37]
I tried upgrading to semantic release v17 today and got this:

```bash
npm WARN semantic-release-slack-bot@1.6.0 requires a peer of semantic-release@>=11.0.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
```

Is there anything stopping us from supporting v17?

If yes, what? Maybe I can fix it.

If no, I can create a PR to bump the peerDependencies key.

**Comment by BeyondEvil** [comment]
v17 requires [node >= 10.18](https://github.com/semantic-release/semantic-release/releases/tag/v17.0.0)

So maybe we make a major (breaking) release with v17 support?

**Comment by juliuscc** [comment]
I think we can try bumping the peerDependencies key. I don't know of any old Node behaviour that would break anything.

**Comment by juliuscc** [comment]
All tests are already running on version 10.5 of Node.

https://github.com/juliuscc/semantic-release-slack-bot/blob/a8bec27f351fe0fa39be0682d4c90ca820210f5b/.circleci/config.yml#L5

For good measure, we can bump this as well to make sure that we comply with 10.18.

**Comment by juliuscc** [comment]
I created a beta release with only these changes. Can you install and see if it works for you?

Install by running:
```
npm i semantic-release-slack-bot@1.6.1-beta.0
```

**Comment by juliuscc** [comment]
I created a PR(#38) with the changes. I'll merge it after your approval.

**Comment by BeyondEvil** [comment]
I'll run through the common path. 👍
