### ISSUE TITLE
Cleanup release template

### ISSUE THREAD

**Issue by paales** [juliuscc/semantic-release-slack-bot#42]
We're using this package with much joy and adds real value for our team. Thanks!

We'd like to simplify the posted Slack message to keep noise as low as possible. I tried to use the `onSuccessTemplate` but that one seems to be missing all required variables.

We currently have this:
![Schermafbeelding 2020-04-22 om 12 17 03](https://user-images.githubusercontent.com/1244416/79970438-33a91780-8493-11ea-8f6b-563ecab596bd.png)

Can we adjust it to:

> **Version [5.8.4]() for [ho-nl/project-reachdigital.nl]() has been released!**
> 
> **Fixes**
> •   ​**metarobots**:​ metaRobots is now required in GraphCMS (fb64921)
>

- Date is redundant as it will send it to Slack immediately after the release has been made.
- The diff link can be found very easily via the release link, so can that can be omitted
- Attachment shows duplicate information already available above.

---

- It would be nice if we could render the homepage url that is entered in the package.json

**Comment by hannesrabo** [comment]
I'm glad to hear that it is useful to you.

Without testing this myself, it sounds like you are after a template that looks something like this.

```js
onSuccessTemplate: {
  type: "section",
  text: {
    type: "mrkdwn",
    text: `Version <$repo_url/releases/tag/$npm_package_version|$npm_package_version> for <$repo_url|$repo_path> has been released!\n$release_notes`
  }
}
```

Let us know if there is anything else missing.

**Comment by juliuscc** [comment]
I am closing this cause it looks solved, but please reopen it if it is not 🙂

**Comment by paales** [comment]
@hannesrabo Oh, I didn't think of the `$repo_url/releases/tag/$npm_package_version`, thanks a lot :)
