### ISSUE TITLE
Release notes markdown format does not look compatible with Slack messages.

### ISSUE THREAD

**Issue by arnaudbesnier** [juliuscc/semantic-release-slack-bot#44]
First of all, thanks for this nice little plugin 🙌🏼

Using the default configuration of the success template, I observe the that the changes displayed in the slack message is not well formatted. See the screenshot below:

<img width="724" alt="Screenshot 2020-05-07 at 11 06 48" src="https://user-images.githubusercontent.com/664261/81276524-6b978980-9053-11ea-8a76-9244aeb425f4.png">

My guess is that Slack does not support standard markdown (according to this 
documentation: https://www.markdownguide.org/tools/slack/).

If I am not wrong a about the issue, as I imagine that Slack won't change its markdown support, it would be great to have an automated translation from standard markdown to Slack markdown.
I would display a nice changelog content in Slack.

_As a workaround, I'll use a custom success template to hide those changes in the message._

**Comment by arnaudbesnier** [comment]
Reading the [code](https://github.com/juliuscc/semantic-release-slack-bot/blob/master/lib/success.js#L41) right now, I understand this is supposed to be done.

Is it a regression, or did I miss something?

**Comment by arnaudbesnier** [comment]
Ok, I missed to set `markdownReleaseNotes` to `true` in my configuration!

**Comment by juliuscc** [comment]
I think we didn't want `markdownReleaseNotes` to be a breaking release when we introduced it. I think we should change the default of this for the next breaking change.
