### ISSUE TITLE
Should we bump slackify-markdown?

### ISSUE THREAD

**Issue by BeyondEvil** [juliuscc/semantic-release-slack-bot#56]
We're using v1.1.1 and the latest release is v3.1.0. @juliuscc

**Comment by juliuscc** [comment]
I think that sounds like a good idea :)

**Comment by juliuscc** [comment]
There is no changelog but I looked at the commits that triggered v2.0.0 and v3.0.0 in slackify-markdown. As far as I can see the changes do not affect us. So it is a safe move :)

**Comment by juliuscc** [comment]
Or one change is that v2 of slackify-markdown supports Nodejs v9 and lower, but I don't think many are stuck at Node v8 (the relevant LTS).

**Comment by juliuscc** [comment]
We would have to bump the supported node version in package.json

**Comment by BeyondEvil** [comment]
Seeing how Node 8 (and 9) isn't even mentioned on the NodeJS [releases](https://nodejs.org/en/about/releases/) page, I'd say we're safe to bump it. Question is if it would warrant a major release? @juliuscc

**Comment by juliuscc** [comment]
I think it would warrant a major release
