### ISSUE TITLE
ENOPACKAGENAME No name for the package defined.

### ISSUE THREAD

**Issue by crobinson42** [juliuscc/semantic-release-slack-bot#59]
```
NPM v6.14.4
Node v14.4.x

   "@semantic-release/changelog": "^5.0.1",
    "@semantic-release/commit-analyzer": "^8.0.1",
    "@semantic-release/git": "^9.0.0",
    "@semantic-release/npm": "^7.0.9",
    "@semantic-release/release-notes-generator": "^9.0.1",
    "semantic-release-slack-bot": "^1.7.0",
```

I get this error and there is a package name in my repo (`@react/common-components`):

```
A name for the package must be created. Run through npm (npm run <semantic-release-script> to use npm package name or define packageName in the plugin config or SEMANTIC_RELEASE_PACKAGE in the environment

AggregateError:
  SemanticReleaseError: No name for the package defined.
  at module.exports (/Users/dasboot/projects/react-common/node_modules/semantic-release-slack-bot/lib/verifyConditions.js:27:11)
at validator (/Users/dasboot/projects/react-common/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
at /Users/dasboot/projects/react-common/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
at next (/Users/dasboot/projects/react-common/node_modules/p-reduce/index.js:17:9)
at /Users/dasboot/projects/react-common/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Object.pluginsConf.<computed> [as verifyConditions] (/Users/dasboot/projects/react-common/node_modules/semantic-release/lib/plugins/index.js:80:11)
  at async run (/Users/dasboot/projects/react-common/node_modules/semantic-release/index.js:95:3)
  at async module.exports (/Users/dasboot/projects/react-common/node_modules/semantic-release/index.js:260:22)
  at async module.exports (/Users/dasboot/projects/react-common/node_modules/semantic-release/cli.js:55:5)% 
```

Here is the `release.config.js` file:

```js
/* eslint-disable */
module.exports = {
  branches: ['master', 'next'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    [
      '@semantic-release/git',
      {
        assets: ['dist/**/*.{js,css}', 'docs', 'package.json'],
        message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
    [
      'semantic-release-slack-bot',
      {
        notifyOnSuccess: true,
        notifyOnFail: true,
      },
    ],
  ],
}
```

It will begin working when adding `packageName: require('./package.json').name` to the plugin config args/opts.

Any thoughts?

**Comment by juliuscc** [comment]
Do you run semantic release with `npx`? Because if so, the plugin will not detect your package name.

**Comment by crobinson42** [comment]
Perhaps this can be an improvement when running with npx? Get the current dir and look for package.json :-)

**Comment by juliuscc** [comment]
Yes, I don't know why this is a problem. We probably read the package name in a suboptimal way cause other plugins work with npx. I warmly welcome a PR that fixes this issue 😁

**Comment by BeyondEvil** [comment]
Easy enough to add. But what should the precedence rules look like? We'll have four ways of providing the package name.

Environment variable
package.json
Config setting
`npm_package_name` <- not sure where this comes from 🤔 

@juliuscc

**Comment by juliuscc** [comment]
Yes the problem is probably that we read `npm_package_name` when there probably exists a better variable given from the context. I am quite sure that other plugins work while doing `npx` and as this plugin is in the later stages the package name should be figured out when it's our time to execute.

**Comment by juliuscc** [comment]
The github plugin gets `relases` from context and then gets `release.name` from them.

See:
- https://github.com/semantic-release/github/blob/1ef0a6d438a6949bbd654ce080d67ec33753409e/lib/get-success-comment.js#L12
- https://github.com/semantic-release/github/blob/1ef0a6d438a6949bbd654ce080d67ec33753409e/lib/success.js#L84
- https://github.com/semantic-release/github/blob/1ef0a6d438a6949bbd654ce080d67ec33753409e/lib/success.js#L45
- https://github.com/semantic-release/github/blob/1ef0a6d438a6949bbd654ce080d67ec33753409e/lib/success.js#L20

**Comment by juliuscc** [comment]
Maybe we could do something similar 🤷

**Comment by romap0** [comment]
@juliuscc Do you have plans to fix that issue?

**Comment by juliuscc** [comment]
This is not a high priority task IMO as there are quite simple workarounds. I do however welcome PR's that fix this. If you need any more assistance than the hints above, I will gladly help 😁
