### ISSUE TITLE
Question: support for Github releases?

### ISSUE THREAD

**Issue by dgattey** [juliuscc/semantic-release-slack-bot#64]
Thanks for a cool sounding plugin for semantic-release! From the README I think the answer is sadly no, but does this repo support Github releases? We have a private Github repo, publishing release notes there, but no NPM package associated. We'd like to be able to post release notes in a slack channel. Can we accomplish that with this tool?

**Comment by juliuscc** [comment]
Yes, that is very much possible. [Semantic-release](https://github.com/semantic-release/semantic-release) supports many plugins, and the GitHub plugin is one of the defaults. This repo is just a plugin for slack and will, therefore, never provide an integration for GitHub releases, but that does not stop you from using this together with the GitHub plugin.

[Here is a list of available plugins](https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md)

The default config looks like this:

```json
{
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/npm",
      "@semantic-release/github"
    ]
  }
}
```

If you want to add slack notifications, you can use this config as a good base:

```json
{
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/npm",
      "@semantic-release/github",
      "semantic-release-slack-bot"
    ]
  }
}
```
