### ISSUE TITLE
Bump dependencies versions

### ISSUE THREAD

**Issue by stelescuraul** [juliuscc/semantic-release-slack-bot#68]
Hi,
There are 3 PRs created for updating the dependencies. 
We are now seeing a `High` severity issue when installing.

![Screenshot_20210511_101556](https://user-images.githubusercontent.com/9428849/117782413-e5072080-b241-11eb-9802-c7ed9f49434f.png)

can we please bump the version of `slackify-markdown` to latest `4.1.0` ? That should fix the issue.

**Comment by stelescuraul** [comment]
I can see that you bumped the version but i believe `chore` commit won't trigger a release. Can we get a trigger for a new release please ? :)

**Comment by juliuscc** [comment]
Yes sorry for not getting to this sooner! It's been a hectic week 😅

**Comment by juliuscc** [comment]
v2.1.1 should be released now 👍
