### ISSUE TITLE
Support for semantic-release@18.0.0

### ISSUE THREAD

**Issue by sreisner** [juliuscc/semantic-release-slack-bot#75]
At the moment the `peerDependencies` rule for the `semantic-release` package in `package.json` requires a version `<18.0.0` is used. Does this library actually not work with `semantic-release@18.0.0` or is that rule just outdated? If it's the latter would you mind if I opened a PR to update the `peerDependencies` rule?

Thank you!

**Comment by juliuscc** [comment]
That is purely outdated. When you do create the PR, could you double-check that it works properly with newer versions of semantic-release?
