### ISSUE TITLE
Slack Message Showing version as a channel (private channel)

### ISSUE THREAD

**Issue by AlissonRS** [juliuscc/semantic-release-slack-bot#93]
Hello!

I loved this plugin for semantic-release, I was able to quickly get started.

Not sure if the issue below is related to this plugin or a problem with slack itself, but slack tries to generate a channel link in the version number since it contains a hashtag.

Would you have any ideas how I can prevent that from happening?

Thanks in advance!!!

![image](https://user-images.githubusercontent.com/4753901/166253079-fdc61119-23e0-4f43-a08b-63e9ce9a0a5b.png)

**Comment by juliuscc** [comment]
Thanks for the positive feedback! ❤️ 

In the image, it looks like the version is `1.3.0-beta.2`. Does the version contain a hashtag somehow? Or is it only that this plugin adds a hashtag?

In other words: do you have a special config where you add `#` to the version? Or do you use pretty default configurations of semantic-release?

**Comment by juliuscc** [comment]
### Update

It looks like we add a hashtag in this place of the code:

https://github.com/juliuscc/semantic-release-slack-bot/blob/9f4c735b5bb8b77404819b9260afeb604d936f9b/lib/success.js#L68-L78

I don't know the reason for that though. It doesn't make sense to me but I would imagine that the symbol is added for a reason. I don't want to just remove it if I break something else.

**Comment by juliuscc** [comment]
### Update 2

The `#` was there from the beginning. It's included in the first commit that posts to slack.

https://github.com/juliuscc/semantic-release-slack-bot/commit/d541e59c84dca0c3e7d0d741361383c24bcfa225

I don't know why no one else hasn't noticed it yet, including me. Could it be that `#` means something else in slack-markdown? In markdown, a `#` means heading but only if it's at the beginning of a line.

**Comment by AlissonRS** [comment]
@juliuscc in slack # is used to reference channels. I'd guess no one has ever noticed that because they are probably slack admins, so slack can figure there is no channel named `1.2.0` (or whatever is the version number) and just ignores the #, but since I'm not admin and the slack from my company has private channels, slack will mask it as a "private channel" rather than ignoring it.

**Comment by AlissonRS** [comment]
@juliuscc I was able to solve it by overriding the template and removing the hashtag:

```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    "@semantic-release/github",
    [
      "semantic-release-slack-bot",
      {
        "packageName": "My Project",
        "notifyOnSuccess": true,
        "notifyOnFail": true,
        "onSuccessTemplate": {
          "text": "A new version of $package_name has been released!",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "A new version of `$package_name` has been released!\nCurrent version is *$npm_package_version*"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "$release_notes"
              }
            }
          ],
          "attachments": [
            {
              "color": "#2cbe4e",
              "blocks": [
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": ":package: *<$repo_url|$repo_path>:*   <$repo_url/releases/tag/v$npm_package_version|v$npm_package_version>"
                    }
                  ]
                }
              ]
            }
          ]
        },
        "markdownReleaseNotes": true,
        "slackWebhook": "https://hooks.slack.com/services/{WEBHOOK_KEY}",
      }
    ]
  ]
}
```

**Comment by juliuscc** [comment]
Perfect! Could you provide a screenshot of how it looks? If it looks good then I think we should create a PR for removing the hashtag.

**Comment by AlissonRS** [comment]
@juliuscc here is a screenshot:

![semantic (1)](https://user-images.githubusercontent.com/4753901/167071880-c8a552a7-42f1-4dfa-83e2-880b7422bfb3.png)

**Comment by juliuscc** [comment]
Thanks for being so helpful! It's great that you took the time to investigate and share a screenshot of the changes.
