### ISSUE TITLE
Is SLACK_ICON and SLACK_NAME working?

### ISSUE THREAD

**Issue by existe-deja** [juliuscc/semantic-release-slack-bot#99]
Hi,

I can't figure it out how the slack bot handle this vars? It's not showing on the posted message.
I use the slack app provided in the readme.

Thanks

**Comment by juliuscc** [comment]
Hi! This is a bit unfortunate but slightly expected. [In the readme](https://github.com/juliuscc/semantic-release-slack-bot#note) we give the following warning:

> [The official documentation](https://api.slack.com/messaging/webhooks) says that a developer cannot override the default name, channel or icon that are associated with the webhook, but some users of this library reported that they were able to.

**Comment by juliuscc** [comment]
So even though some users have been able to use them it seems like the behavior follows the documentation for you.

Did I correctly understand the question? Otherwise please reopen this issue. 😁

**Comment by existe-deja** [comment]
Completely. I just didn't read this line :sweat_smile: 
Thanks

**Comment by juliuscc** [comment]
I think that the documentation is a little confusing. If you have any suggestions on how to improve them you are very welcome to open a new issue or a PR. I would welcome it! 😁
